backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: 'content/sales-page.md'
        label: 'Página de vendas'
        name: "sales_page"
        fields:
          - label: 'Hero Section'
            name: 'hero'
            widget: 'object'
            fields:
              - label: 'Headline'
                name: 'headline'
                widget: 'string'
              - label: 'Subheadline'
                name: 'subheadline'
                widget: 'string'
              - label: 'CTA Button'
                name: 'cta_button'
                widget: 'object'
                fields:
                  - label: 'Label'
                    name: 'label'
                    widget: 'string'
                  - label: 'URL'
                    name: 'url'
                    widget: 'string'
              - label: 'Background Image'
                name: 'bg_image'
                widget: 'image'
              - label: 'Logo'
                name: 'logo'
                widget: 'image'
              - label: 'Display Logo?'
                name: 'display_logo'
                widget: 'boolean'
          - label: 'Benefits Section'
            name: 'benefits'
            widget: 'object'
            fields:
              - label: 'Headline'
                name: 'headline'
                widget: 'string'
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'List of Benefits'
                name: 'benefits_list'
                widget: 'list'
          - label: 'Methodology Section'
            name: 'methodology'
            widget: 'object'
            fields:
              - label: 'Headline'
                name: 'headline'
                widget: 'string'
              - label: 'Method Description'
                name: 'method_description'
                widget: 'markdown'
          - label: 'Social Proof Section'
            name: 'social_proof'
            widget: 'object'
            fields:
              - label: 'Style'
                name: 'style'
                widget: 'select'
                options: ['Image List', 'Facebook Widget']
              - label: 'Images'
                name: 'images'
                widget: 'list'
                types:
                  - label: 'Image'
                    name: 'image'
                    widget: 'image'
          - label: 'Course Author Bio'
            name: 'author_bio'
            widget: 'object'
            fields:
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Headline'
                name: 'headline'
                widget: 'string'
              - label: 'Content'
                name: 'content'
                widget: 'markdown'
          - label: 'Course Modules'
            name: 'course_modules'
            widget: 'list'
            fields:
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Description'
                name: 'description'
                widget: 'string'
          - label: 'Course Bonuses'
            name: 'course_bonuses'
            widget: 'list'
            fields:
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Description'
                name: 'description'
                widget: 'string'
              - label: 'Value'
                name: 'value'
                widget: 'number'
          - label: 'Offer Section'
            name: 'offer_section'
            widget: 'object'
            fields:
              - label: 'Headline'
                name: 'headline'
                widget: 'string'
              - label: 'List of Deliverables'
                name: 'deliverables'
                widget: 'list'
              - label: 'Pre-discount Price'
                name: 'pre_discount_price'
                widget: 'string'
              - label: 'Post-discount Price'
                name: 'post_discount_price'
                widget: 'string'
              - label: 'CTA Button'
                name: 'cta_button'
                widget: 'object'
                fields:
                  - label: 'Label'
                    name: 'label'
                    widget: 'string'
                  - label: 'URL'
                    name: 'url'
                    widget: 'string'
                  - label: 'Color'
                    name: 'color'
                    widget: 'string'
                  - label: 'Pulse Button?'
                    name: 'pulse_button'
                    widget: 'boolean'
          - label: 'Guarantee Section'
            name: 'guarantee_section'
            widget: 'object'
            fields:
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Headline'
                name: 'headline'
                widget: 'string'
              - label: 'Description'
                name: 'description'
                widget: 'markdown'
              - label: 'CTA Button'
                name: 'cta_button'
                widget: 'object'
                fields:
                  - label: 'Label'
                    name: 'label'
                    widget: 'string'
                  - label: 'URL'
                    name: 'url'
                    widget: 'string'
          - label: 'FAQ Section'
            name: 'faq_section'
            widget: 'list'
            fields:
              - label: 'Question'
                name: 'question'
                widget: 'string'
              - label: 'Answer'
                name: 'answer'
                widget: 'markdown'
          - label: 'Author Bio'
            name: 'author_bio_final'
            widget: 'object'
            fields:
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Headline'
                name: 'headline'
                widget: 'string'
              - label: 'Description'
                name: 'description'
                widget: 'markdown'
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "site/data/footer.json"
        label: Footer
        name: footer
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Blurb, name: blurb, widget: text}
      - file: "site/config.toml"
        label: Hugo Config
        name: config
        editor:
          preview: false
        fields:
          - {label: Site Title for Browser Tab, name: title, widget: string}
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
